/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCourseModal: typeof import('./src/components/modals/AddCourseModal.vue')['default']
    AddTaskModal: typeof import('./src/components/modals/AddTaskModal.vue')['default']
    AssessmentCard: typeof import('./src/components/cards/AssessmentCard.vue')['default']
    CalendarWidget: typeof import('./src/components/dashboard/CalendarWidget.vue')['default']
    CourseCard: typeof import('./src/components/cards/CourseCard.vue')['default']
    DeleteCourseModal: typeof import('./src/components/modals/DeleteCourseModal.vue')['default']
    DeleteTaskModal: typeof import('./src/components/modals/DeleteTaskModal.vue')['default']
    EditTaskModal: typeof import('./src/components/modals/EditTaskModal.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ResultCount: typeof import('./src/components/table/ResultCount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/dashboard/StatsCard.vue')['default']
    TableRows: typeof import('./src/components/table/TableRows.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UpcomingAssessments: typeof import('./src/components/dashboard/UpcomingAssessments.vue')['default']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
