/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssementCard: typeof import('./src/components/AssementCard.vue')['default']
    AssessmentCard: typeof import('./src/components/cards/AssessmentCard.vue')['default']
    AssessmentCardCard: typeof import('./src/components/AssessmentCardCard.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    CalendarWidget: typeof import('./src/components/dashboard/CalendarWidget.vue')['default']
    CourseCard: typeof import('./src/components/cards/CourseCard.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/dashboard/StatsCard.vue')['default']
    UpcomingAssements: typeof import('./src/components/UpcomingAssements.vue')['default']
    UpcomingAssessments: typeof import('./src/components/UpcomingAssessments.vue')['default']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
